"""Deterministically merge team-owned requirements/*.in files."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from security_eval.errors import ContractError

NAME_PATTERN = re.compile(r"^\s*([A-Za-z0-9_.-]+)")


def normalize_name(requirement: str) -> str:
    match = NAME_PATTERN.match(requirement)
    if not match:
        raise ContractError(f"Cannot parse requirement line: {requirement}")
    return match.group(1).lower().replace("_", "-").replace(".", "-")


def merge_requirement_files(paths: list[Path]) -> list[str]:
    merged: dict[str, str] = {}
    for path in sorted(paths, key=lambda item: item.name):
        if not path.exists():
            continue
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            name = normalize_name(line)
            previous = merged.get(name)
            if previous is not None and previous != line:
                raise ContractError(
                    f"Conflicting requirements for {name}: {previous!r} versus {line!r}"
                )
            merged[name] = line
    return [merged[name] for name in sorted(merged)]


def write_requirements(lines: list[str], output: Path, sources: list[Path]) -> None:
    header = [
        "# Generated by scripts/merge_requirements.py; do not edit directly.",
        "# Sources: " + ", ".join(path.as_posix() for path in sources if path.exists()),
        "",
    ]
    output.write_text("\n".join(header + lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--requirements-dir", type=Path, default=Path("requirements"))
    parser.add_argument("--output", type=Path, default=Path("requirements.txt"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    sources = sorted(args.requirements_dir.glob("*.in"))
    try:
        lines = merge_requirement_files(sources)
        write_requirements(lines, args.output, sources)
    except ContractError as exc:
        print(f"requirements merge failed: {exc}")
        return 1
    print(f"wrote {args.output} with {len(lines)} direct requirements")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
